enum SolutionStatus {
	SOLUTION_STATUS__SUCCESS,
	SOLUTION_STATUS__ERROR
};
enum FlushNoteStatus {
	FLUSH_NOTE_STATUS__CONTINUE,
	FLUSH_NOTE_STATUS__ERROR,
	FLUSH_NOTE_STATUS__RECHECK
};
enum AreaType {
	AREA_TYPE__ROW,
	AREA_TYPE__COLUMN,
	AREA_TYPE__SUBGRID
};
enum OutputMode {
	OUTPUT_MODE__PLAIN,
	OUTPUT_MODE__NOTE
};
enum InputStatus {
	INPUT_STATUS__SUCCESS,
	INPUT_STATUS__EOF
};
enum FillNoteStatus {
	FILL_NOTE_STATUS__SUCCESS,
	FILL_NOTE_STATUS__ERROR
};